maintainers: Update maintainer policy
opiproject/opi pull request #29
Opened 2022-09-07 18:24 UTC by mestery

Per discussion on the mailing list [1], this commit updates the maintaienr policy to propose adding two new groups with merge rights. We will end up with 3 different groups with merge rights if this change is approved by the OPI TSC:

* An `opi-tsc` group which can merge into the main opi repository [2]
* An `opi-outreach` group which can merge into the website repository [3]
* The existing `opi-maintainers` group which can merge into all OPI repositories.

[1] https://lists.opiproject.org/g/tsc/message/36
[2] https://github.com/opiproject/opi
[3] https://github.com/opiproject/opiproject.org

Signed-off-by: Kyle Mestery <mestery@mestery.com>

2022-09-07 18:25 UTC, mestery commented
Starting 4 business day review window.

2022-09-07 18:28 UTC, seroyer approved these changes
Wonderful!

2022-09-07 22:09 UTC, glimchb requested changes
I don't like having more then 1 maintainers list/group

2022-09-08 14:32 UTC, glimchb approved these changes
TSC voted to merge this, so removing my objection

2022-09-08 14:32 UTC, merged